name: Build and Release Web Scraper

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    name: Build Go Binary
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/web-scraper-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-scraper-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/web-scraper-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Release Binary
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create release assets
        run: |
          cd dist
          for file in web-scraper-*; do
            chmod +x "$file"
            zip "$file.zip" "$file"
          done

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
